update Installation.md
Kindling-project/kindling pull request #102
Opened 2022-03-10 13:01 UTC by sugary199

Signed-off-by: sugary199 <906940958@qq.com>

2022-03-10 13:02 UTC, sugary199 commented
1、change the command of cloning branch code
2、The copy operation usually reports an error because the previous absolute path is different
3、There is also a scripts folder below the agent-lib directory，we need go back to probe directory

2022-03-10 13:10 UTC, dxsup commented
Anyway, I think this PR could be merged except for the comment I left above, as it will spend some time to finish the new documentation.

2022-03-11 05:48 UTC, dxsup requested changes

2022-03-14 02:34 UTC, dxsup approved these changes

2022-03-14 02:35 UTC, merged

2022-03-14 02:35 UTC, dxsup commented
Close #96