[WIP] optimize the structure of kindling event
Kindling-project/kindling pull request #160
Opened 2022-03-30 08:03 UTC by sanyangji

We notice that the current struct of kindling event is sort of bad for performance so we have to make some change on it to improve performance.
The first step is to replace AnyValue with KeyValue that consists of name, valueType and the value in format of bytes. Using AnyValue, we can easily to get value while it adds pressure for object allocation and GC. Instead, we can infer the attributes based on KeyValue which may save more resources (CPU and MEM).

After changing, we will test to make a comparision.

2022-04-02 07:24 UTC, sanyangji commented on collector/model/kindling_event_helper.go
> +func (x *KindlingEvent) GetUintUserAtrribute(key string) uint64 {
All get method may have typo problem, should be Attribute.

2022-04-06 07:15 UTC, dxsup requested changes

2022-04-06 07:15 UTC, dxsup commented on collector/analyzer/tcpmetricanalyzer/tcp_analyzer.go
> +	dPortUint := event.GetUintUserAttribute("dport")
There are several variables above called `sIp`, `sPort`, `dIp`, and `dPort`  which could be reused. I think we better check the value before using it as there are a lot of empty values for these events.

2022-04-06 08:41 UTC, dxsup approved these changes
LGTM

2022-04-06 08:58 UTC, merged